export interface TrainCardItemProp {
    id: string;
    trainNumber: string;
    trainTrackFrom: string;
    trainTrackTo: string;
    departureTimeThere: string;
    departureCityThere: string;
    departureStationThere: string;
    timeTrackThere: string;
    arrivalTimeThere: string;
    arrivalCityThere: string;
    arrivalStationThere: string;
    departureTimeBack: string;
    departureCityBack: string;
    departureStationBack: string;
    timeTrackBack: string;
    arrivalTimeBack: string;
    arrivalCityBack: string;
    arrivalStationBack: string;
    dataTrainType: TrainType[];
}

export interface TrainType {
    trainType: string;
    trainAmount: string;
    trainPrice: string;
}

export const data_trainCard: TrainCardItemProp[] = [
    {
        id: '1',
        trainNumber: '116C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16:00:30:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '18:30',
        arrivalTimeThere: '2024-10-16T06:00:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '40',
                trainPrice: '1 920',
            },
            {
                trainType: 'Плацкарт',
                trainAmount: '20',
                trainPrice: '2 530',
            },
            {
                trainType: 'Купе',
                trainAmount: '10',
                trainPrice: '3 820',
            },
            {
                trainType: 'Люкс',
                trainAmount: '6',
                trainPrice: '4 950',
            },
        ],
    },
    {
        id: '2',
        trainNumber: '117C',
        trainTrackFrom: 'Казань',
        trainTrackTo: 'Адлер',
        departureTimeThere: '2024-10-16T01:00:00+03:00',
        departureCityThere: 'Казань',
        departureStationThere: 'Казанский вокзал',
        timeTrackThere: '09:30',
        arrivalTimeThere: '2024-10-16T09:40:00+03:00',
        arrivalCityThere: 'Адлер',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Адлер',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T09:10:00+03:00',
        arrivalCityBack: 'Казань',
        arrivalStationBack: 'Казанский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '40',
                trainPrice: '1 920',
            },
            {
                trainType: 'Плацкарт',
                trainAmount: '25',
                trainPrice: '2 530',
            },
        ],
    },
    {
        id: '3',
        trainNumber: '118C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T01:30:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '09:30',
        arrivalTimeThere: '2024-10-16T10:00:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            {
                trainType: 'Купе',
                trainAmount: '15',
                trainPrice: '3 820',
            },
            {
                trainType: 'Люкс',
                trainAmount: '6',
                trainPrice: '4 950',
            },
        ],
    },
    {
        id: '4',
        trainNumber: '119C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T02:00:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '09:30',
        arrivalTimeThere: '2024-10-16T10:30:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '40',
                trainPrice: '1 920',
            },
            {
                trainType: 'Люкс',
                trainAmount: '5',
                trainPrice: '4 950',
            },
        ],
    },
    {
        id: '5',
        trainNumber: '120C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T02:30:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '09:30',
        arrivalTimeThere: '2024-10-16T10:40:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '10',
                trainPrice: '1 920',
            },
            {
                trainType: 'Плацкарт',
                trainAmount: '20',
                trainPrice: '2 530',
            },
            {
                trainType: 'Купе',
                trainAmount: '30',
                trainPrice: '3 820',
            },
            {
                trainType: 'Люкс',
                trainAmount: '40',
                trainPrice: '4 950',
            },
        ],
    },
    {
        id: '6',
        trainNumber: '121C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T03:00:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '09:30',
        arrivalTimeThere: '2024-10-16T11:40:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '88',
                trainPrice: '1 920',
            },
            {
                trainType: 'Плацкарт',
                trainAmount: '52',
                trainPrice: '2 530',
            },
        ],
    },
    {
        id: '7',
        trainNumber: '122C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T03:30:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '00:25',
        arrivalTimeThere: '2024-10-16T11:40:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '88',
                trainPrice: '1 920',
            },
            {
                trainType: 'Плацкарт',
                trainAmount: '52',
                trainPrice: '2 530',
            },
            {
                trainType: 'Купе',
                trainAmount: '24',
                trainPrice: '3 820',
            },
            {
                trainType: 'Люкс',
                trainAmount: '15',
                trainPrice: '4 950',
            },
        ],
    },
    {
        id: '8',
        trainNumber: '123C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T04:00:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '09:30',
        arrivalTimeThere: '2024-10-16T12:30:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            {
                trainType: 'Купе',
                trainAmount: '24',
                trainPrice: '3 820',
            },
        ],
    },
    {
        id: '9',
        trainNumber: '124C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T04:30:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '09:30',
        arrivalTimeThere: '2024-10-16T12:50:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '88',
                trainPrice: '1 920',
            },
        ],
    },
    {
        id: '10',
        trainNumber: '125C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T05:00:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '09:30',
        arrivalTimeThere: '2024-10-16T13:20:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '88',
                trainPrice: '1 920',
            },
            {
                trainType: 'Люкс',
                trainAmount: '15',
                trainPrice: '4 950',
            },
        ],
    },
    {
        id: '11',
        trainNumber: '126C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T05:30:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '07:15',
        arrivalTimeThere: '2024-10-16T13:50:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '88',
                trainPrice: '1 920',
            },
            {
                trainType: 'Плацкарт',
                trainAmount: '52',
                trainPrice: '2 530',
            },
            {
                trainType: 'Купе',
                trainAmount: '24',
                trainPrice: '3 820',
            },
            {
                trainType: 'Люкс',
                trainAmount: '15',
                trainPrice: '4 950',
            },
        ],
    },
    {
        id: '12',
        trainNumber: '127C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T06:00:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '07:30',
        arrivalTimeThere: '2024-10-16T14:00:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '88',
                trainPrice: '1 920',
            },
            {
                trainType: 'Купе',
                trainAmount: '24',
                trainPrice: '3 820',
            },
            {
                trainType: 'Люкс',
                trainAmount: '15',
                trainPrice: '4 950',
            },
        ],
    },
    {
        id: '13',
        trainNumber: '128C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T06:30:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '00:30',
        arrivalTimeThere: '2024-10-16T14:40:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '88',
                trainPrice: '1 920',
            },
            {
                trainType: 'Плацкарт',
                trainAmount: '52',
                trainPrice: '2 530',
            },
            {
                trainType: 'Купе',
                trainAmount: '24',
                trainPrice: '3 820',
            },
            {
                trainType: 'Люкс',
                trainAmount: '15',
                trainPrice: '4 950',
            },
        ],
    },
    {
        id: '14',
        trainNumber: '129C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T07:00:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '08:30',
        arrivalTimeThere: '2024-10-16T15:00:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            { 
                trainType: 'Сидячий',
                trainAmount: '88',
                trainPrice: '1 920',
            },
            {
                trainType: 'Плацкарт',
                trainAmount: '52',
                trainPrice: '2 530',
            },
        ],
    },
    {
        id: '15',
        trainNumber: '130C',
        trainTrackFrom: 'Москва',
        trainTrackTo: 'Санкт-Петербург',
        departureTimeThere: '2024-10-16T07:30:00+03:00',
        departureCityThere: 'Москва',
        departureStationThere: 'Курский вокзал',
        timeTrackThere: '09:40',
        arrivalTimeThere: '2024-10-16T15:50:00+03:00',
        arrivalCityThere: 'Санкт-Петербург',
        arrivalStationThere: 'Московский вокзал',
        departureTimeBack: '2024-10-16T23:40:00+03:00',
        departureCityBack: 'Санкт-Петербург',
        departureStationBack: 'Московский вокзал',
        timeTrackBack: '08:30',
        arrivalTimeBack: '2024-10-17T08:10:00+03:00',
        arrivalCityBack: 'Москва',
        arrivalStationBack: 'Курский вокзал',
        dataTrainType: [
            {
                trainType: 'Плацкарт',
                trainAmount: '52',
                trainPrice: '2 530',
            },
            {
                trainType: 'Люкс',
                trainAmount: '15',
                trainPrice: '4 950',
            },
        ],
    },

];
